"""Add ondelete CASCADE to favorites foreign keys

Revision ID: 074ec231e912
Revises: 102ad414ed63
Create Date: 2025-07-07 09:49:02.281962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074ec231e912'
down_revision: Union[str, None] = '102ad414ed63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favorites_user_uid_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_product_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_product_id_fkey'), 'favorites', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('favorites_user_uid_fkey'), 'favorites', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###
