"""Fix order_id type mismatch

Revision ID: 3927472cec49
Revises: f4c15802c2cb
Create Date: 2025-08-01 11:09:16.837938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3927472cec49'
down_revision: Union[str, None] = 'f4c15802c2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(), nullable=False))
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'orders', ['payment_id'])
    op.create_foreign_key(None, 'orders', 'payments', ['payment_id'], ['id'])
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payments', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_column('payments', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
