"""Updated Product model with new fields

Revision ID: 3ac9319bf4eb
Revises: 
Create Date: 2025-05-22 10:01:20.044265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ac9319bf4eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sizes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('colors', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('products', 'colors')
    op.drop_column('products', 'sizes')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'discount')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'images')
    # ### end Alembic commands ###
