"""Add currency column to payments

Revision ID: 61a5cc1962be
Revises: df8bc54ee77a
Create Date: 2025-06-05 10:41:20.680895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a5cc1962be'
down_revision: Union[str, None] = 'df8bc54ee77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_product_unique', 'favorites', ['user_uid', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_unique', 'favorites', type_='unique')
    # ### end Alembic commands ###
